### ISSUE TITLE
Update to 1.18.1?

### ISSUE THREAD

**Issue by Kichura** [TechStreetDev/Map-Crash-Fixer-Mod#1]
When trying to force this mod to work with 1.18.x, the client will just crash cuz mixins are incompatible.

**Comment by TechStreetDev** [comment]
Hiya, I will make a version of this mod for 1.18 and 1.18.1 with teller the next 24hours!

**Comment by TechStreetDev** [comment]
The 1.18 has been created and can be found at https://github.com/TechStreetDev/Map-Crash-Fixer-Mod/actions/runs/1570376093

**Comment by Kichura** [comment]
Build has failed due to a broken code string.

**Comment by TechStreetDev** [comment]
Thats strange (i just assumed it would work because it worked on localhost build)

**Comment by TechStreetDev** [comment]
Ok looking at mc code this issue will no longer happen with 1.18 and above

**Comment by TechStreetDev** [comment]
This project is now archived
